instagram_web/blueprints/users/views.py
import flask
from flask import Blueprint, g
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.utils import secure_filename
from peewee import IntegrityError, Model
from PIL import Image

# importing related to User & it's forms
from models.user import User, Relationship
from models.post import Post
# from models.relationship import Relationship
from instagram_web.blueprints.users.forms import RegistrationForm, LoginForm, UpdateDetailsForm

# Common import that shares with the posts.py
from flask import render_template, redirect, url_for, flash, request, session, escape
from flask_login import login_user, logout_user, login_required, current_user
from app import app

# import aws_s3 helper
from instagram_web.util.s3_helper import upload_file_to_s3, random_file_name

users_blueprint = Blueprint('users',
							__name__,
							template_folder='templates/users')


# OAuth sections
from flask_dance.contrib.github import make_github_blueprint, github
github_blueprint = make_github_blueprint(client_id='f2bbc19d909797496071', client_secret='3be3e6bd1126a19456e72a1d94882f855b6228f2')
app.register_blueprint(github_blueprint, url_prefix='/github_login')

# Google Auth
from authlib.client import OAuth2Session
import google.oauth2.credentials
import googleapiclient.discovery
from oauth2client.file import Storage

@users_blueprint.route('/github')
def github_login():
	if not github.authorized:
		return redirect(url_for('github.login'))

	account_info = github.com.get('/user')

	if account_info.ok:
		account_info_json = account_info.json()
		github_username = account_info_json['login']
		flash("Login via Github is successful", 'success')
		return redirect(url_for('users.index'))
	flash('Error occured while logging in via Github', 'danger')
	return redirect(url_for('users.index', username=github_username))
	# github does not allow http -> https
	# need to allow special permission 
	# for linux: "export OAUTHLIB_INSECURE_TRANSPORT=1"
	# for windows: "set OAUTHLIB_INSECURE_TRANSPORT=1"

def redirect_if_logged_in():
	if current_user.is_authenticated:
		flash("You have already been logged in", "warning")
		return redirect(url_for('users.index'))

"""Start of index"""
@users_blueprint.route('/', methods=["GET"])
def index():
	"""
	Need to retrieve the posts where current user is "ALLOWED" to follow
	1. Select posts whom current user is following
		a. if followee.is_public == False
		b. Need to ensure Relationship is approved by followee
	2. Select posts from self
	"""
	posts = None
	if current_user.is_authenticated:
		try:
			posts = Post.select().where(
				(Post.user_id == current_user.following()) | (Post.user_id == current_user.id)
			).order_by(Post.updated_at.desc())
		except:
			flash("There are no posts to be displayed, start following people", "info")
		finally:
			return render_template('index.html', posts=posts)
	else:
		return render_template('index.html', posts=posts)

"""End of index"""

"""
Start of View User Profile
"""
@users_blueprint.route('/<string:username>', methods=["GET"])
def display_user(username):
	user = User.get_or_none(User.username == username)
	posts = Post.select().where(Post.user == user)
	return render_template('user.html', user=user, posts=posts)
"""
End of View User Profile
"""


"""
Start of Register User
"""
@users_blueprint.route('/register', methods=['GET'])
def display_register():
	redirect_if_logged_in()
	form = RegistrationForm()
	return render_template('register.html', register_form=form)

@users_blueprint.route('/register', methods=['POST'])
def register_user():
	form = RegistrationForm()
	if form.validate_on_submit():
		try:
			new_user = User(
				username=form.data['username'],
				email=form.data['email'],
				password=generate_password_hash(form.data['password'])
			)
			new_user.save()
			flash("Thanks for registering", "success")
			return redirect(url_for('users.display_login'))
		except IntegrityError:
			flash('Duplication of either username or email', 'warning')
	return render_template('register.html', register_form=form)
"""
End of Register User
"""

"""
Start of Login User
"""
@users_blueprint.route('/login', methods=['GET'])
def display_login():
	redirect_if_logged_in()
	form = LoginForm()
	return render_template('login.html', login_form=form)

@users_blueprint.route('/login', methods=['POST'])
def log_user():
	form = LoginForm()
	next_page = request.args.get('next')
	if form.validate_on_submit():
		user = User.get_or_none(User.email == form.data['email'])
		if user != None:
			password = check_password_hash(user.password, form.password.data)
			if password:
				login_user(user)
				flash("You've been logged in!", "success")
				if next_page:
					return redirect(url_for(next_page))
				else:
					return redirect(url_for('users.index'))
			else:
				flash("Please recheck the password entered", "warning")
		else:
			flash("There is no account associated with the particular address", "danger")
	return render_template('login.html', login_form=form)
"""
End of Login User
"""


"""
Start of Update User
"""
@users_blueprint.route('/update', methods=['GET'])
def display_update():
	form = UpdateDetailsForm()
	form.username.data = current_user.username
	form.email.data = current_user.email
	post_count = Post.select().where(Post.user == current_user)
	followers_count = current_user.followers()
	following_count = current_user.following()
	return render_template('update.html', form=form, username=current_user.username, email=current_user.email, post_count=post_count, followers_count=followers_count, following_count=following_count)

ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg', 'gif'])
def allowed_file(filename):
	return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


# temporarily allow posting of image
# suppose to update profile
@users_blueprint.route('/update', methods=['POST'])
@login_required
def update_user():
	form = UpdateDetailsForm()
	username_test = User.get_or_none(User.username == form.username.data)
	email_test = User.get_or_none(User.email == form.email.data)
	# A
	if "picture" not in request.files:
		flash("No picture key in request.files", 'danger')
		return redirect(url_for('users.update_user'))
	# B
	file = request.files['picture']
	# C
	if file.filename == '':
		flash("Please select a file", 'danger')
		return redirect(url_for('users.update_user'))
	# D
	if file and allowed_file(file.filename):
		file.filename = secure_filename(file.filename)
		output = upload_file_to_s3(file, app.config['S3_BUCKET'])
		# print(output)
		current_user.image_file = output
		# current_user.save()
		try:
			updated_user = User.update(
				username=form.username.data,
				email=form.email.data,
				password=generate_password_hash(form.password.data),
				image_file=output,
				is_public=form.is_public.data
			).where(User == current_user)
		except IntegrityError:
			flash('Duplication of either username or email', 'warning')
		else:
			updated_user.execute() # does this create new or update??
			flash('Data saved', 'success')
			# if username_test == None and email_test == None:
			# else:
			# 	flash('Duplication of either username or email', 'warning')
		return redirect(url_for('users.index'))
	else:
		return redirect("/")
	# 	# meant for the condition of success
"""
End of Update User
"""

@users_blueprint.route('/logout')
@login_required
def logout():
	logout_user()
	flash("You've been logged out!", "success")
	return redirect(url_for('users.index'))

"""
Google Auth
"""

ACCESS_TOKEN_URI = 'https://www.googleapis.com/oauth2/v4/token'
AUTHORIZATION_URL = 'https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent'

AUTHORIZATION_SCOPE ='openid email profile'

AUTH_TOKEN_KEY = 'auth_token'
AUTH_STATE_KEY = 'auth_state'
USER_INFO_KEY = 'user_info'

@users_blueprint.route('/google/login')
def google_login():
	session = OAuth2Session(app.config['GOOGLE_CLIENT_ID'], app.config['GOOGLE_CLIENT_SECRET'], scope=app.config['GOOGLE_AUTHORIZATION_SCOPE'], redirect_uri=url_for('users.index'))
	uri, state = session.authorization_url(AUTHORIZATION_URL)
	flask.session[AUTH_STATE_KEY] = state
	session.permanent = True
	return redirect(uri, code=302)

@users_blueprint.route('/google/auth')
def google_auth_redirect():
	state = request.args.get('state', default=None, type=None)
	session = OAuth2Session(app.config['GOOGLE_CLIENT_ID'], app.config['GOOGLE_CLIENT_SECRET'], scope=app.config['GOOGLE_AUTHORIZATION_SCOPE'], state=state, redirect_uri=url_for('users.index'))
	oauth2_tokens = session.fetch_access_token(ACCESS_TOKEN_URI, authorization_response=request.url)
	flask.session[AUTH_TOKEN_KEY] = oauth2_tokens
	return redirect(url_for('users.index'))

def build_credentials():
	oauth2_tokens = session[AUTH_TOKEN_KEY]
	return google.oauth2.credentials.Credentials(
		oauth2_tokens['access_token'],
		refresh_token=oauth2_tokens['refresh_token'],
		client_id=app.config['GOOGLE_CLIENT_ID'],
		client_secret=app.config['GOOGLE_CLIENT_SECRET'],
		token_uri=ACCESS_TOKEN_URI
	)

def get_user_info():
	credentials = build_credentials()
	oauth2_client = googleapiclient.discovery.build('oauth2', 'v2', credentials=credentials)
	return oauth2_client.userinfo().get().execute()

def store_user_info():
	user = get_user_info()
	storage = Storage()
	storage.put(user)
	# How to determine whether the user has signed up with us?
	# How to save the user credentials inside the database?
	credentials = storage.get()
	# What is the purpose of the line above?? For login?

"""
Start of Follow and Unfollow Users
"""
@users_blueprint.route('/follow/<string:username>', methods=['POST'])
@login_required
def follow(username):
	try:
		from_user=User.select().where(User.username == current_user.username)
		to_user=User.select().where(User.username == username)
	except User.DoesNotExist:
		pass
	else:
		# breakpoint()
		try:
			new_relationship = Relationship.create(
				from_user_id=from_user[0].id,
				to_user_id=to_user[0].id,

instagram_web/blueprints/users/templates/users/current_user_card.html
<div class="media">
    <img src="{{ current_user.image_file }}" alt="User Image" class="rounded-circle account-img">
    <div class="media-body">
        <h2 class="account-heading">{{ current_user.username }}</h2>
        <p class="text-secondary">{{ current_user.email }}</p>
        <div class="container">
            <div class="row">
                <div>Posts <small>{{ current_user.posts.count() }}</small></div>
                <div>Followers <small>{{ current_user.followers().count() }}</small></div>
                <div>Following <small>{{ current_user.following().count() }}</small></div>
            </div>
        </div>
    </div>
</div>

instagram_web/blueprints/users/templates/users/display_post.html
<div class="container">
	<div class="row">
		{% for post in posts %}
		<div class="col-sm-12 col-md-6 col-lg-4 my-4">
			<div class="card">
				<img class="card-img-top" src="{{ post.picture }}" alt="Post Picture">
				<div class="card-body">
					<div class="d-flex justify-content-start status-container">
						<div class="status">
							<input type="checkbox" name="emoji" id="smile">
							<label for="smile" class="icon icon-smile"></label>
							<span>2</span>
						</div>
						<div class="status">
							<input type="checkbox" name="emoji" id="shocked">
							<label for="shocked" class="icon icon-shocked"></label>
							<span>2</span>
						</div>
						<div class="status">
							<input type="checkbox" name="emoji" id="sad">
							<label for="sad" class="icon icon-sad"></label>
							<span>2</span>
						</div>
					</div>
					<div class="d-flex justify-content-between mt-2">
						<div><a href="{{ url_for('users.display_user', username=post.user.username)}}">{{ post.user.username }}</a></div>
						<div>{{ post.updated_at.strftime('%Y-%m-%d') }}</div>
					</div>
					<h3>{{ post.title }}</h3>
					<p>{{ post.content }}</p>
					{% if post.user != current_user %}
					<form action="{{ url_for('donations.new_donation') }}">
						<input type="submit" value="Donate" class="btn btn-primary">
					</form>
					{% endif %}

					<script src="https://js.braintreegateway.com/web/dropin/1.16.0/js/dropin.min.js"></script>
					<script>
						var form = document.querySelector('#payment-form');
						var client_token = '{{ client_token }}';
						braintree.dropin.create({
							authorization: client_token,
							container: '#bt-dropin'
							// paypal: {
							//	flow: 'vault'
							//}
						}, function (createErr, instance) {
							form.addEventListener('submit', function (event) {
								event.preventDefault();
								instance.requestPaymentMethod(function (err, payload) {
									if (err) {
										console.log('Error', err);
										return;
									}
									// Add the nonce to the form and submit
									document.querySelector('#nonce').value = payload.nonce;
									form.submit();
								});
							});
						});
					</script>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</div>

instagram_web/blueprints/users/templates/users/follower_request.html
{% extends "_layout.html" %}

{% block content %}
{% include "current_user_card.html" %}
<legend>Follower Request</legend>
<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">From</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody class="table-striped">
        {% for requester in requests %}
        <tr>
            <th scope="row">{{ loop.index }}</th>
            <td><a href="{{ url_for('users.display_user', username=requester.username) }}">{{ requester.username }}</a></td>
            <td>
                <form action="{{ url_for('users.approve_request', approval=current_user.id) }}" method="POST">
                    <h2>{{ current_user.username }}</h2>
                    <input type="submit" class="btn btn-success" value="Approve">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

instagram_web/blueprints/users/templates/users/index.html
{% include "_layout.html" %}

{% if current_user.is_anonymous %}
    {% include "welcome.html" %}
{% else %}
    {% if posts %}
        {% include "display_post.html" %}
    {% else %}
        <h5>No posts</h5>
    {% endif %}
{% endif %}

instagram_web/blueprints/users/templates/users/login.html
{% include "_layout.html" %}
<div class="container">
	{% include "login_form.html" %}

	<div class="border-top py-3">
		<small class="text-muted">
			Login using Google instead <a class="ml-2 btn btn-dark" href="{{ url_for('users.google_login') }}"><i class="icon icon-google3"></i></a>
		</small>
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Do not have an account ? <a class="ml-2" href="{{ url_for('users.display_register') }}">Register</a>
		</small>
	</div>
</div>

instagram_web/blueprints/users/templates/users/login_form.html
{% block content %}
<div class="content-section">
	<form method="POST" action="" enctype="multipart/form-data">
		{{ login_form.csrf_token }}
		{{ login_form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Sign In</legend>
			<div class="form-group">
				{{ login_form.email.label(class="form-control-label") }}
				{% if login_form.email.errors %}
				{{ login_form.email(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in login_form.email.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ login_form.email(class="form-control form-control-lg") }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ login_form.password.label(class="form-control-label") }}
				{% if login_form.password.errors %}
				{{ login_form.password(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in login_form.password.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ login_form.password(class="form-control form-control-lg") }}
				{% endif %}
			</div>
		</fieldset>
		<div class="form-group">
			{{ login_form.btn(class="btn btn-outline-info", id='Login') }}
			<!-- <input type="submit" class="btn btn-outline-info" value="Login" name="btn"> -->
		</div>
	</form>
</div>
{% endblock content %}

instagram_web/blueprints/users/templates/users/register.html
{% include "_layout.html" %}
<div class="container">
	{% include "register_form.html" %}
	<div class="border-top py-3">
		<div class="d-flex justify-content-between">
			<a href="{{ url_for('users.github_login') }}" class="icon icon-google3"></a>
			<a class="icon icon-github"></a>
			<a class="icon icon-smile"></a>
			<a class="icon icon-smile"></a>
		</div>
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Already Have An Account? <a class="ml-2" href="{{ url_for('users.display_login') }}">Sign In</a>
		</small>
	</div>
</div>

instagram_web/blueprints/users/templates/users/register_form.html
{% block content %}
<div class="content-section">
	<form method="POST" action="" enctype="multipart/form-data">
		{{ register_form.csrf_token }}
		{{ register_form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Join Today</legend>
			<div class="form-group">
				{{ register_form.username.label(class="form-control-label") }}

				{% if register_form.username.errors %}
				{{ register_form.username(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in register_form.username.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ register_form.username(class="form-control form-control-lg") }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ register_form.email.label(class="form-control-label") }}
				{% if register_form.email.errors %}
				{{ register_form.email(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in register_form.email.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ register_form.email(class="form-control form-control-lg") }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ register_form.password.label(class="form-control-label") }}
				{% if register_form.password.errors %}
				{{ register_form.password(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in register_form.password.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ register_form.password(class="form-control form-control-lg") }}
				{% endif %}
			</div>
		</fieldset>
		<div class="form-group">
			{{ register_form.btn(class="btn btn-outline-info", id='Register') }}
			<!-- <input type="submit" class="btn btn-outline-info" value="Register" name="btn"> -->
		</div>
	</form>
</div>
{% endblock content %}

instagram_web/blueprints/users/templates/users/update.html
{% extends "_layout.html" %}
{% block content %}
<div class="content-section">
	{% include "current_user_card.html" %}
	<form method="POST" action="" enctype="multipart/form-data">
		{{ form.csrf_token }}
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Update Profile</legend>
			<div class="form-group">
				{{ form.username.label(class="form-control-label") }}

				{% if form.username.errors %}
				{{ form.username(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.username.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.username(class="form-control form-control-lg", value=username) }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.email.label(class="form-control-label") }}
				{% if form.email.errors %}
				{{ form.email(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.email.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.email(class="form-control form-control-lg", value=email) }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.password.label(class="form-control-label") }}
				{% if form.password.errors %}
				{{ form.password(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.password.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.password(class="form-control form-control-lg") }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.picture.label(class="form-control-label") }}
				{% if form.picture.errors %}
				{{ form.picture(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.picture.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.picture(class="form-control form-control-lg") }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.is_private.label(class="form-control-label") }}
				{% if form.is_private.errors %}
				{{ form.is_private(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.is_private.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				<div class="checkbox left-checkbox">
					{{ form.is_private(class="left-checkbox") }}
				</div>
				{% endif %}
			</div>
		</fieldset>
		<div class="form-group">
			{{ form.submit(class="btn btn-outline-info") }}
		</div>
	</form>
</div>
{% endblock content %}

instagram_web/blueprints/users/templates/users/user.html
{% extends "_layout.html" %}
{% block content %}
<div class="content-section">
{% include "user_card.html" %}
</div>
{% if posts %}
{% include "display_post.html" %}
{% else %}
<h3 class="text-center">No posts</h3>
{% endif %}

{% endblock %}

instagram_web/blueprints/users/templates/users/user_card.html
<div class="media">
	<img src="{{ user.image_file }}" alt="User Image" class="rounded-circle account-img">
	<div class="media-body">
		<h2 class="account-heading">{{ user.username }}</h2>
		<p class="text-secondary">{{ user.email }}</p>
		<div class="container">
			<div class="row">
				<div>Posts <small>{{ user.posts.count() }}</small></div>
				<div>Followers <small>{{ user.followers().count() }}</small></div>
				<div>Following <small>{{ user.following().count() }}</small></div>
			</div>
			<div class="row">
				<!-- Display the follow and unfollow button -->
				{% if current_user.is_authenticated %}
					{% if user != current_user %}
						{% if not user in current_user.following() %}
							<form action="{{ url_for('users.follow', username=user.username) }}" method="POST">
								<input type="submit" class="btn btn-success" value="Follow">
								<input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
							</form>
						{% else %}
							<form action="{{ url_for('users.unfollow', username=user.username) }}" method="POST">
								<input type="submit" class="btn btn-secondary" value="Unfollow">
								<input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
							</form>
						{% endif %}
					{% endif %}
				{% endif %}
			</div>
		</div>
	</div>
</div>