instagram_web/blueprints/donations/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, FileField, TextAreaField, SubmitField, DateField
from wtforms.validators import DataRequired

class CreateDonateForm(FlaskForm):
	amount = FileField(
		'Amount',
		validators=[
			DataRequired()
		]
	)
	card_number = StringField(
		'Card Number',
		validators=[
			DataRequired()
		]
	)
	expiry_date = DateField(
		'Expiry Date MM/YY',
		validators=[
			DataRequired()
		]
	)
	submit = SubmitField('Donate')

instagram_web/blueprints/donations/views.py
from flask import Blueprint
import braintree

# importing related to Donation & it's forms
from models.post import Post
from models.donation import Donation
from instagram_web.blueprints.donations.forms import CreateDonateForm

# Common import that shares with the posts.py
from flask import render_template, redirect, url_for, flash, request, session, escape, abort
from flask_login import login_user, logout_user, login_required, current_user
from app import app

from instagram_web.util.gateway import generate_client_token, transact, find_transaction

donations_blueprint = Blueprint('donations',
							__name__,
							template_folder='templates/donations')

# from instagram_web.blueprints.posts.views import posts_blueprint

TRANSACTION_SUCCESS_STATUSES = [
	braintree.Transaction.Status.Authorized,
	braintree.Transaction.Status.Authorizing,
	braintree.Transaction.Status.Settled,
	braintree.Transaction.Status.SettlementConfirmed,
	braintree.Transaction.Status.SettlementPending,
	braintree.Transaction.Status.Settling,
	braintree.Transaction.Status.SubmittedForSettlement
]

@donations_blueprint.route('/new', methods=["GET"])
def new_donation():
	client_token = generate_client_token()
	return render_template('new.html', client_token=client_token)

@donations_blueprint.route('/<transaction_id>', methods=['GET'])
def show_checkout(transaction_id):
	transaction = find_transaction(transaction_id)
	result = {}
	if transaction.status in TRANSACTION_SUCCESS_STATUSES:
		result = {
			'header': 'Sweet Success!',
			'icon': 'success',
			'message': 'Your test transaction has been successfully processed. See the Braintree API response and try again.'
		}
	else:
		result = {
			'header': 'Transaction Failed',
			'icon': 'fail',
			'message': 'Your test transaction has a status of ' + transaction.status + '. See the Braintree API response and try again.'
		}

	return render_template('/show.html', transaction=transaction, result=result)

@donations_blueprint.route('/', methods=['POST'])
def create_checkout():
	result = transact({
		'amount': request.form['amount'],
		'payment_method_nonce': request.form['payment_method_nonce'],
		'options': {
			"submit_for_settlement": True
		}
	})

	if result.is_success or result.transaction:
		"""
		Create a donation and save it to database for record
		"""
		# Start of code
		try:
			donor_id = current_user.id
			recipient_id = post.user.id
			new_donation = Donation(
				donor_id = donor_id,
				recipient_id = recipient_id,
				post_id = post_id,
				amount = form.amount.data
			)
		except:
			flash("Error while processing, kindly retry", 'danger')
		else:
			new_donation.save()
			flash('Donation performed', 'success')
		# End of code
		return redirect(url_for('donations.show_checkout',transaction_id=result.transaction.id))
	else:
		for x in result.errors.deep_errors:
			flash('Error: %s: %s' % (x.code, x.message))
		# breakpoint()
		return redirect(url_for('donations.new_donation'))

# @donations_blueprint.route('<int:post_id>/donate', methods=["POST"])
# @login_required
# def create_donation(post_id):
# 	form = CreateDonateForm()
# 	if form.validate_on_submit():
# 		try:
# 			donor_id = current_user.id
# 			post = Post.get_or_none(Post.id == post_id)
# 			recipient_id = post.user.id
# 			new_donation = Donation(
# 				donor_id = donor_id,
# 				recipient_id = recipient_id,
# 				post_id = post_id,
# 				amount = form.amount.data
# 			)
# 		except:
# 			flash("Error while processing, kindly retry", 'danger')
# 		else:
# 			new_donation.save()
# 			flash('Donation performed', 'success')
# 			return redirect(url_for('users.index'))
# 	return render_template('create_donation.html', form=form)

instagram_web/blueprints/donations/templates/donations/new.html
{% extends '_layout.html' %}
{% block content %}

<div class="wrapper">
	<div class="checkout container">

		<header>
			<h1>Hi, <br>Let's test a transaction</h1>
			<p>
				Make a test payment with Braintree using PayPal or a card
			</p>
		</header>

		<form id="payment-form" method="post" action="{{ url_for('donations.create_checkout') }}">
			<section>
				<label for="amount">
					<span class="input-label">Amount</span>
					<div class="input-wrapper amount-wrapper">
						<input id="amount" name="amount" type="tel" min="1" placeholder="Amount" value="10">
					</div>
				</label>

				<div class="bt-drop-in-wrapper">
					<div id="bt-dropin"></div>
				</div>
			</section>
			<input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
			<input type="hidden" id="nonce" name="payment_method_nonce" />
			<button class="button" type="submit" id="submit-button"><span>Test Transaction</span></button>
		</form>

	</div>
</div>

<script src="https://js.braintreegateway.com/web/dropin/1.16.0/js/dropin.min.js"></script>
<script>
	var form = document.querySelector('#payment-form');
	var client_token = '{{ client_token }}';
	braintree.dropin.create({
		authorization: client_token,
		container: '#bt-dropin',
		paypal: {
			flow: 'vault'
		}
	}, function (createErr, instance) {
		form.addEventListener('submit', function (event) {
			event.preventDefault();
			instance.requestPaymentMethod(function (err, payload) {
				if (err) {
					console.log('Error', err);
					return;
				}
				// Add the nonce to the form and submit
				document.querySelector('#nonce').value = payload.nonce;
				form.submit();
			});
		});
	});
</script>
{% endblock %}

instagram_web/blueprints/donations/templates/donations/show.html
{% extends '_layout.html' %}
{% block content %}

<div class="wrapper">
  <div class="response container">
	<div class="content">
	  <div class="icon">
		<img src="/static/images/{{ result['icon'] }}.svg" alt="">
	  </div>

	  <h1>{{ result['header'] }}</h1>
	  <section>
		<p>{{ result['message'] }}</p>
	  </section>

	  <section>
		<a class="button primary back" href="/checkouts/new">
		  <span>Test Another Transaction</span>
		</a>
	  </section>
	</div>
  </div>
</div>

<aside class="drawer dark">
  <header>
	<div class="content compact">
	  <a href="https://developers.braintreepayments.com" class="braintree" target="_blank">Braintree</a>
	  <h3>API Response</h3>
	</div>
  </header>

  <article class="content compact">
  <section>
	<h5>Transaction</h5>
	  <table cellpadding="0" cellspacing="0">
		<tbody>
		  <tr>
			<td>id</td>
			<td>{{ transaction.id }}</td>
		  </tr>
		  <tr>
			<td>type</td>
			<td>{{ transaction.type }}</td>
		  </tr>
		  <tr>
			<td>amount</td>
			<td>{{ transaction.amount }}</td>
		  </tr>
		  <tr>
			<td>status</td>
			<td>{{ transaction.status }}</td>
		  </tr>
		  <tr>
			<td>created_at</td>
			<td>{{ transaction.created_at }}</td>
		  </tr>
		  <tr>
			<td>updated_at</td>
			<td>{{ transaction.updated_at }}</td>
		  </tr>
		</tbody>
	  </table>
	</section>

	<section>
	  <h5>Payment</h5>

	  <table cellpadding="0" cellspacing="0">
		<tbody>
		  <tr>
			<td>token</td>
			<td>{{ transaction.credit_card_details.token }}</td>
		  </tr>
		  <tr>
			<td>bin</td>
			<td>{{ transaction.credit_card_details.bin }}</td>
		  </tr>
		  <tr>
			<td>last_4</td>
			<td>{{ transaction.credit_card_details.last_4 }}</td>
		  </tr>
		  <tr>
			<td>card_type</td>
			<td>{{ transaction.credit_card_details.card_type }}</td>
		  </tr>
		  <tr>
			<td>expiration_date</td>
			<td>{{ transaction.credit_card_details.expiration_date }}</td>
		  </tr>
		  <tr>
			<td>cardholder_name</td>
			<td>{{ transaction.credit_card_details.cardholder_name }}</td>
		  </tr>
		  <tr>
			<td>customer_location</td>
			<td>{{ transaction.credit_card_details.customer_location }}</td>
		  </tr>
		</tbody>
	  </table>
	</section>

	{% if transaction.customer_details.id %}
	  <section>
		<h5>Customer Details</h5>
		<table cellpadding="0" cellspacing="0">
		  <tbody>
			<tr>
			  <td>id</td>
			  <td>{{ transaction.customer_details.id }}</td>
			</tr>
			<tr>
			  <td>first_name</td>
			  <td>{{ transaction.customer_details.first_name }}</td>
			</tr>
			<tr>
			  <td>last_name</td>
			  <td>{{ transaction.customer_details.last_name }}</td>
			</tr>
			<tr>
			  <td>email</td>
			  <td>{{ transaction.customer_details.email }}</td>
			</tr>
			<tr>
			  <td>company</td>
			  <td>{{ transaction.customer_details.company }}</td>
			</tr>
			<tr>
			  <td>website</td>
			  <td>{{ transaction.customer_details.website }}</td>
			</tr>
			<tr>
			  <td>phone</td>
			  <td>{{ transaction.customer_details.phone }}</td>
			</tr>
			<tr>
			  <td>fax</td>
			  <td>{{ transaction.customer_details.fax }}</td>
			</tr>
		  </tbody>
		</table>
	  </section>
	{% endif %}

	<section>
	  <p class="center small">Integrate with the Braintree SDK for a secure and seamless checkout</p>
	</section>

	<section>
	  <a class="button secondary full" href="https://developers.braintreepayments.com/guides/drop-in" target="_blank">
		<span>See the Docs</span>
	  </a>
	</section>
  </article>
</aside>
{% endblock %}